### ISSUE TITLE
When downloading: 403 client error: forbidden for url: https://music.google.com/music/export/....

### ISSUE THREAD

**Issue by aaltemara** [jaymoulin/google-music-manager#13]
I'm seeing an issue where the gmusicapi successfully logs, the downloader queries for songs, but then appears to fail when getting the download link.

any ideas on what is wrong?

command output:
```

$ google-music-download --directory /mnt/...SNIP...
INFO:google_music_manager_downloader.download:Init Daemon - Press Ctrl+C to quit
INFO:gmusicapi.Musicmanager1:!-- begin debug log --!
INFO:gmusicapi.Musicmanager1:version: 11.0.3
INFO:gmusicapi.Musicmanager1:logging to: /home/...SNIP....
INFO:gmusicapi.Musicmanager1:initialized
INFO:gmusicapi.Musicmanager1:logged out
INFO:oauth2client.client:Refreshing access_token
INFO:gmusicapi.Musicmanager1:oauth successful
DEBUG:gmusicapi.Musicmanager1:AuthenticateUploader(args=['...SNIP...]', '...SNIP... (gmusicapi-11.0.3)'], kwargs={})
DEBUG:gmusicapi.Musicmanager1:response_type: AUTH_RESPONSE
policy {
  pause_uploads: false
  abort: false
  retry_in_minutes: 5
  bandwidth_cap_kbps: 12000
  pause_downloads: false
  download_bandwidth_cap_kbps: 16000
  send_analytics: false
  enable_gapless: true
  enable_m4p: true
}
auth_status: OK
auth_error: false
upauth_response {
  uploader_id: "...SNIP..."
}

INFO:gmusicapi.Musicmanager1:successful upauth
DEBUG:gmusicapi.Musicmanager1:ListTracks(args=['...SNIP...', None, 1], kwargs={})
DEBUG:gmusicapi.Musicmanager1:<1000 songs>, updated_min: 1448555023308000, continuation_token: '...SNIP...'
DEBUG:gmusicapi.Musicmanager1:ListTracks(args=['...SNIP...', '...SNIP......', 1], kwargs={})
DEBUG:gmusicapi.Musicmanager1:<1000 songs>, updated_min: 1448555163201000, continuation_token: '...SNIP...'
DEBUG:gmusicapi.Musicmanager1:ListTracks(args=['...SNIP...', '...SNIP......', 1], kwargs={})
DEBUG:gmusicapi.Musicmanager1:<1000 songs>, updated_min: 1533234598918000, continuation_token: '...SNIP...'
DEBUG:gmusicapi.Musicmanager1:ListTracks(args=['...SNIP...', '...SNIP......', 1], kwargs={})
DEBUG:gmusicapi.Musicmanager1:<0 songs>, updated_min: None, continuation_token: None
DEBUG:gmusicapi.Musicmanager1:GetDownloadLink(args=['927e1305-a452-31b6-bcb7-04fd5ea491fc', '...SNIP...'], kwargs={})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gmusicapi/protocol/shared.py", line 218, in perform
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://music.google.com/music/export?version=2&songid=927e1305-a452-31b6-bcb7-04fd5ea491fc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/google-music-download", line 11, in <module>
    load_entry_point('google-music-manager-downloader==1.1.0', 'console_scripts', 'google-music-download')()
  File "/usr/local/lib/python3.6/site-packages/google_music_manager_downloader/download.py", line 37, in main
    download(args.directory, args.oauth)
  File "/usr/local/lib/python3.6/site-packages/google_music_manager_downloader/download.py", line 25, in download
    filename, audio = api.download_song(song['id'])
  File "<decorator-gen-70>", line 2, in download_song
  File "/usr/local/lib/python3.6/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/gmusicapi/clients/musicmanager.py", line 380, in download_song
    self.uploader_id)['url']
  File "/usr/local/lib/python3.6/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: GetDownloadLink: 403 Client Error: Forbidden for url: https://music.google.com/music/export?version=2&songid=927e1305-a452-31b6-bcb7-04fd5ea491fc
(requests kwargs: {'method': 'GET', 'url': 'https://music.google.com/music/export', 'headers': {'X-Device-ID': '...SNIP...', 'Authorization': '<omitted>'}, 'params': {'version': 2, 'songid': '927e1305-a452-31b6-bcb7-04fd5ea491fc'}})
(response was: '<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')

```

One thing that may be strange, is in the gmusicapi.log, it gives: 
gmusicapi.Musicmanager1 (musicmanager:232) [INFO]: successful upauth

But I'm trying to download, not upload.

**Comment by jaymoulin** [comment]
Looks like you'll need to define a device_id. I have to add a feature for that

**Comment by jaymoulin** [comment]
A `device_id` is definable when launching the program. I give your eth0 interface MAC address by default so it may work just by updating to `1.2.0`. If not, consider adding this parameter when launching the program
