### ISSUE TITLE
Error running uploader-daemon.py

### ISSUE THREAD

**Issue by sphr2k** [jaymoulin/google-music-manager#2]
Hi,

I tried to set up your app according to the readme in a Docker container. I successfully added the OAuth token, but when running uploader-daemon.py, I receive the following below.

On "My Devices", there are 7 devices registered (10 allowed), so I think that's not really the cause.

Might this be related to [this issue](https://github.com/simon-weber/gmusicapi/issues/543)?

Any feedback would be appreciated :)

Thanks,
Jan

```
INFO:__main__:Init Daemon - Press Ctrl+C to quit
INFO:gmusicapi.Musicmanager1:!-- begin debug log --!
INFO:gmusicapi.Musicmanager1:version: 10.1.2
INFO:gmusicapi.Musicmanager1:logging to: /root/.cache/gmusicapi/log/gmusicapi.log
INFO:gmusicapi.Musicmanager1:initialized
INFO:gmusicapi.Musicmanager1:logged out
INFO:oauth2client.client:Refreshing access_token
INFO:gmusicapi.Musicmanager1:oauth successful
DEBUG:gmusicapi.Musicmanager1:AuthenticateUploader(args=['02:42:AC:16:00:03', '0fb43b22e367 (gmusicapi-10.1.2)'], kwargs={})
DEBUG:gmusicapi.Musicmanager1:response_type: AUTH_RESPONSE
policy {
  pause_uploads: false
  abort: false
  retry_in_minutes: 5
  bandwidth_cap_kbps: 12000
  pause_downloads: false
  download_bandwidth_cap_kbps: 16000
  send_analytics: false
  enable_gapless: true
  enable_m4p: true
}
auth_status: MAX_PER_MACHINE_USERS_EXCEEDED
auth_error: false
upauth_response {
  uploader_id: "02:42:AC:16:00:03"
}

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/shared.py", line 247, in perform
    cls.check_success(response, parsed_response)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/musicmanager.py", line 135, in check_success
    ), cls.__name__
gmusicapi.exceptions.CallFailure: AuthenticateUploader: Upload auth error code 12: MAX_PER_MACHINE_USERS_EXCEEDED. See http://goo.gl/O6xe7 for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/musicmanager.py", line 231, in _perform_upauth
    uploader_name)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/shared.py", line 261, in perform
    raise_from(CallFailure(err_msg, e.callname), e)
  File "<string>", line 2, in raise_from
gmusicapi.exceptions.CallFailure: AuthenticateUploader: AuthenticateUploader: Upload auth error code 12: MAX_PER_MACHINE_USERS_EXCEEDED. See http://goo.gl/O6xe7 for more information.
(requests kwargs: {'data': b'\n\x1102:42:AC:16:00:03\x12\x1f0fb43b22e367 (gmusicapi-10.1.2)', 'headers': {'User-agent': 'Music Manager (1, 0, 55, 7425 HTTPS - Windows)', 'Authorization': '<omitted>'}, 'method': 'POST', 'url': 'https://android.clients.google.com/upsj/upauth'})
(response was: '\x08\x062\x14\x08\x00\x10\x00\x18\x05 \xe0](\x000\x80}8\x00H\x01P\x01X\x0c`\x00j\x13\n\x1102:42:AC:16:00:03')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 1687: ordinal not in range(128)
Call stack:
  File "./uploader-daemon.py", line 46, in <module>
    if api.login(oauth):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/musicmanager.py", line 170, in login
    self._perform_upauth(uploader_id, uploader_name))
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/musicmanager.py", line 237, in _perform_upauth
    self.logger.exception("upauth failure")
Message: 'upauth failure'
Arguments: ()
2017-07-30 11:28:40,072 - gmusicapi.Musicmanager1 (musicmanager:237) [ERROR]: upauth failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/shared.py", line 247, in perform
    cls.check_success(response, parsed_response)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/musicmanager.py", line 135, in check_success
    ), cls.__name__
gmusicapi.exceptions.CallFailure: AuthenticateUploader: Upload auth error code 12: MAX_PER_MACHINE_USERS_EXCEEDED. See http://goo.gl/O6xe7 for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/musicmanager.py", line 231, in _perform_upauth
    uploader_name)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/shared.py", line 261, in perform
    raise_from(CallFailure(err_msg, e.callname), e)
  File "<string>", line 2, in raise_from
gmusicapi.exceptions.CallFailure: AuthenticateUploader: AuthenticateUploader: Upload auth error code 12: MAX_PER_MACHINE_USERS_EXCEEDED. See http://goo.gl/O6xe7 for more information.
(requests kwargs: {'data': b'\n\x1102:42:AC:16:00:03\x12\x1f0fb43b22e367 (gmusicapi-10.1.2)', 'headers': {'User-agent': 'Music Manager (1, 0, 55, 7425 HTTPS - Windows)', 'Authorization': '<omitted>'}, 'method': 'POST', 'url': 'https://android.clients.google.com/upsj/upauth'})
(response was: '\x08\x062\x14\x08\x00\x10\x00\x18\x05 \xe0](\x000\x80}8\x00H\x01P\x01X\x0c`\x00j\x13\n\x1102:42:AC:16:00:03')
ERROR:gmusicapi.Musicmanager1:upauth failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/shared.py", line 247, in perform
    cls.check_success(response, parsed_response)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/musicmanager.py", line 135, in check_success
    ), cls.__name__
gmusicapi.exceptions.CallFailure: AuthenticateUploader: Upload auth error code 12: MAX_PER_MACHINE_USERS_EXCEEDED. See http://goo.gl/O6xe7 for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/musicmanager.py", line 231, in _perform_upauth
    uploader_name)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/shared.py", line 261, in perform
    raise_from(CallFailure(err_msg, e.callname), e)
  File "<string>", line 2, in raise_from
gmusicapi.exceptions.CallFailure: AuthenticateUploader: AuthenticateUploader: Upload auth error code 12: MAX_PER_MACHINE_USERS_EXCEEDED. See http://goo.gl/O6xe7 for more information.
(requests kwargs: {'data': b'\n\x1102:42:AC:16:00:03\x12\x1f0fb43b22e367 (gmusicapi-10.1.2)', 'headers': {'User-agent': 'Music Manager (1, 0, 55, 7425 HTTPS - Windows)', 'Authorization': '<omitted>'}, 'method': 'POST', 'url': 'https://android.clients.google.com/upsj/upauth'})
(response was: '\x08\x062\x14\x08\x00\x10\x00\x18\x05 \xe0](\x000\x80}8\x00H\x01P\x01X\x0c`\x00j\x13\n\x1102:42:AC:16:00:03')
Error with oauth credentials
```

**Comment by jaymoulin** [comment]
You're right, that's related. Did you try deleting all related docker containers and your key to start over?

**Comment by sphr2k** [comment]
Hi, 
I started from scratch several times, but I didn't change the code yet. Could you give me the hint what to change in order to manually specify a MAC address (as suggested [here](https://github.com/simon-weber/gmusicapi/issues/543#issuecomment-292882432))?

Thx, Jan

**Comment by sphr2k** [comment]
Great thanks, will try this tonight :)
